"""Render the capability table from the reviewed operation inventory."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render() -> str:
    rows = json.loads((ROOT / "contracts/surfaces.json").read_text())
    lines = [
        "# interface capabilities",
        "",
        "Generated by `just surfaces`; edit `contracts/surfaces.json`.",
        "",
        "| SDK (sync and async) | CLI | MCP |",
        "| --- | --- | --- |",
    ]
    for row in rows:
        cli = f"`plyrfm {row['cli']}`" if row["cli"] else row["cli_note"]
        mcp = f"`{row['mcp']}`" if row["mcp"] else row["mcp_note"]
        lines.append(f"| `{row['sdk']}` | {cli} | {mcp} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "docs/surfaces.md"
    expected = render()
    if args.check:
        if not path.exists() or path.read_text() != expected:
            raise SystemExit("Capability docs are stale; run just surfaces")
    else:
        path.write_text(expected)


if __name__ == "__main__":
    main()
